INSERT INTO programs (name, explanation) VALUES
    ("Attack on Titan", "A world where giant humanoid creatures threaten humanity's existence."),
    ("Stranger Things", "A group of kids in a small town encounter supernatural mysteries."),
    ("My Hero Academia", "In a world where most of the population has superpowers, a young boy strives to become a hero."),
    ("Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine."),
    ("Naruto", "A young ninja seeks recognition from his peers and dreams of becoming the strongest ninja."),
    ("The Witcher", "A monster hunter navigates a world filled with magical creatures and political intrigue."),
    ("Black Mirror", "Anthology series exploring the dark and often dystopian aspects of technology."),
    ("Game of Thrones", "Political and dynastic struggles for control of the Iron Throne in the Seven Kingdoms."),
    ("One Piece", "A pirate with a goal to find the legendary One Piece treasure and become the Pirate King."),
    ("The Mandalorian", "A lone bounty hunter explores the outer reaches of the galaxy in the Star Wars universe."),
    ("Lost", "Survivors of a plane crash must navigate a mysterious island."),
    ("The Office", "A mockumentary-style sitcom depicting the daily lives of office employees."),
    ("Avatar: The Last Airbender", "A young boy must master the elements to bring balance to the world."),
    ("Prison Break", "A man deliberately gets imprisoned to help his wrongly accused brother escape."),
    ("Desperate Housewives", "The lives of suburban women with a dark secret intertwine."),
    ("Dexter", "A blood-spatter analyst leads a secret life as a vigilante serial killer."),
    ("Friends", "A group of friends in New York navigate the ups and downs of life and love."),
    ("The Sopranos", "A mob boss balances the demands of his crime family with those of his personal life."),
    ("Firefly", "A ragtag crew navigates a futuristic universe after the fall of a galactic government."),
    ("24", "Counter-terrorism agent Jack Bauer races against time to thwart various threats."),
    ("The Wire", "Explores the city of Baltimore through the eyes of both law enforcement and drug dealers."),
    ("House", "A brilliant but unconventional doctor leads a team of diagnosticians."),
    ("Grey's Anatomy", "Medical drama following the personal and professional lives of surgical interns."),
    ("Battlestar Galactica", "Humans and their AI creations, the Cylons, engage in an interstellar war."),
    ("Alias", "A double agent balances a secret life while working for a covert branch of the CIA."),
    ("Stranger Things", "A group of kids in a small town encounter supernatural mysteries."),
    ("Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine."),
    ("Game of Thrones", "Political and dynastic struggles for control of the Iron Throne in the Seven Kingdoms."),
    ("Black Mirror", "Anthology series exploring the dark and often dystopian aspects of technology."),
    ("The Mandalorian", "A lone bounty hunter explores the outer reaches of the galaxy in the Star Wars universe."),
    ("Fleabag", "A witty and troubled woman navigates life and love in London."),
    ("Westworld", "An amusement park with advanced AI hosts blurs the line between reality and fantasy."),
    ("The Crown", "Chronicles the reign of Queen Elizabeth II and the events that shaped the second half of the 20th century."),
    ("Stray Kids", "Reality show following a South Korean boy band as they train and compete."),
    ("The Witcher", "A monster hunter navigates a world filled with magical creatures and political intrigue."),
    ("Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine."),
    ("The Handmaid's Tale", "In a dystopian society, women are subjugated and forced into reproductive servitude."),
    ("Sherlock", "Modern adaptation of Arthur Conan Doyle's detective stories."),
    ("Money Heist", "A group of criminals executes an elaborate plan to rob the Royal Mint of Spain."),
    ("The Umbrella Academy", "A dysfunctional family of adopted superhero siblings reunites to solve the mystery of their father's death."),
    ("Mr. Robot", "A cybersecurity expert becomes involved in an underground hacking group."),
    ("Narcos", "Chronicles the rise and fall of the notorious drug lord Pablo Escobar."),
    ("Jessica Jones", "A former superhero with PTSD opens her own detective agency."),
    ("The Man in the High Castle", "In an alternate history, the Axis powers won World War II, leading to a divided United States."),
    ("Master of None", "Follows the personal and professional life of an actor in New York."),
    ("Making a Murderer", "True crime documentary series examining the case of Steven Avery."),
    ("Better Call Saul", "A prequel to Breaking Bad, focusing on the transformation of Jimmy McGill into Saul Goodman."),
    ("The Revenant", "A frontiersman fights for survival after being mauled by a bear and left for dead."),
    ("Mad Max: Fury Road", "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler."),
    ("Inside Out", "Animated film exploring the emotions inside a young girl's mind."),
    ("The Hateful Eight", "In post-Civil War Wyoming, strangers are stranded by a blizzard and may not be who they seem."),
    ("The Martian", "Astronaut stranded on Mars must find a way to survive and signal for rescue."),
    ("Sicario", "FBI agents join a task force to combat drug cartels on the U.S.-Mexico border."),
    ("Star Wars: The Force Awakens", "New heroes and villains emerge in the galaxy far, far away."),
    ("Stranger Things", "A group of kids in a small town encounter supernatural mysteries."),
    ("Haikyuu!!", "A high school volleyball team strives to reach the national championships."),
    ("Demon Slayer: Kimetsu no Yaiba", "A young boy becomes a demon slayer to avenge his family and save his demon-turned sister."),
    ("Jujutsu Kaisen", "A high school student battles curses and learns the art of jujutsu to protect others."),
    ("Your Lie in April", "A talented pianist finds new purpose in life through a violinist with a secret."),
    ("One Punch Man", "A hero who can defeat any opponent with a single punch seeks a worthy challenge."),
    ("Tokyo Revengers", "A man discovers he can time travel and attempts to prevent a tragic future."),
    ("Attack on Titan", "A world where giant humanoid creatures threaten humanity's existence."),
    ("One Piece", "A pirate with a goal to find the legendary One Piece treasure and become the Pirate King."),
    ("My Hero Academia", "In a world where most of the population has superpowers, a young boy strives to become a hero."),
    ("Re:Zero - Starting Life in Another World", "A young man finds himself in a fantasy world and discovers he can return from death."),
    ("Sword Art Online", "Players become trapped in a virtual reality MMORPG, where death in the game means death in real life."),
    ("Cowboy Bebop", "Bounty hunters travel through space in pursuit of the galaxy's most dangerous criminals."),
    ("Steins;Gate", "A group of friends accidentally invent a time machine with unintended consequences."),
    ("Fullmetal Alchemist: Brotherhood", "Two brothers seek the Philosopher's Stone to restore their bodies after a failed alchemical ritual."),
    ("Death Note", "A high school student gains the power to kill anyone by writing their name in a supernatural notebook."),
    ("Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine."),
    ("Stranger Things", "A group of kids in a small town encounter supernatural mysteries."),
    ("Game of Thrones", "Political and dynastic struggles for control of the Iron Throne in the Seven Kingdoms."),
    ("Black Mirror", "Anthology series exploring the dark and often dystopian aspects of technology."),
    ("The Mandalorian", "A lone bounty hunter explores the outer reaches of the galaxy in the Star Wars universe."),
    ("Fleabag", "A witty and troubled woman navigates life and love in London."),
    ("Westworld", "An amusement park with advanced AI hosts blurs the line between reality and fantasy."),
    ("The Crown", "Chronicles the reign of Queen Elizabeth II and the events that shaped the second half of the 20th century."),
    ("Stray Kids", "Reality show following a South Korean boy band as they train and compete."),
    ("The Witcher", "A monster hunter navigates a world filled with magical creatures and political intrigue."),
    ("Breaking Bad", "A high school chemistry teacher turns to cooking and selling methamphetamine."),
    ("The Handmaid's Tale", "In a dystopian society, women are subjugated and forced into reproductive servitude."),
    ("Sherlock", "Modern adaptation of Arthur Conan Doyle's detective stories."),
    ("Money Heist", "A group of criminals executes an elaborate plan to rob the Royal Mint of Spain."),
    ("The Umbrella Academy", "A dysfunctional family of adopted superhero siblings reunites to solve the mystery of their father's death."),
    ("The Haunting of Hill House", "A family confronts traumatic events from their past after growing up in a haunted house."),
    ("Bodyguard", "A war veteran turned bodyguard is assigned to protect a politician with a complicated personal life."),
    ("Homecoming", "A caseworker at a transitional support center helps soldiers transition back to civilian life."),
    ("Killing Eve", "An MI6 agent and a psychopathic assassin become obsessed with each other."),
    ("Sharp Objects", "A journalist returns to her hometown to cover the murder of two young girls."),
    ("The Assassination of Gianni Versace: American Crime Story", "Chronicles the murder of fashion designer Gianni Versace."),
    ("The Chilling Adventures of Sabrina", "A teenage witch navigates the challenges of balancing her dual nature."),
    ("The Marvelous Mrs. Maisel", "A housewife pursues a career in stand-up comedy in 1950s New York."),
    ("Ozark", "A financial planner relocates his family to the Ozarks to launder money for a Mexican drug cartel."),
    ("Pose", "Explores the ball culture in 1980s New York and the LGBTQ community."),
    ("Succession", "A dysfunctional family fights for control of a global media conglomerate."),
    ("The Terror", "A Royal Navy expedition in 1845 encounters mysterious and deadly forces in the Arctic."),
    ("Westworld", "An amusement park with advanced AI hosts blurs the line between reality and fantasy."),
    ("Atlanta", "Follows two cousins as they navigate the Atlanta rap scene."),
    ("The Americans", "A married couple of Soviet spies pose as ordinary Americans during the Cold War."),
    ("Chernobyl", "Dramatization of the 1986 nuclear disaster and its aftermath."),
    ("Watchmen", "Set in an alternate history where superheroes are treated as outlaws."),
    ("When They See Us", "Chronicles the wrongful conviction of five young men in the Central Park jogger case."),
    ("The Mandalorian", "A lone bounty hunter explores the outer reaches of the galaxy in the Star Wars universe."),
    ("The Witcher", "A monster hunter navigates a world filled with magical creatures and political intrigue."),
    ("Euphoria", "Follows a group of high school students as they navigate love, friendship, and addiction."),
    ("Mindhunter", "FBI agents investigate and profile serial killers in the late 1970s."),
    ("Stranger Things", "A group of kids in a small town encounter supernatural mysteries."),
    ("Succession", "A dysfunctional family fights for control of a global media conglomerate."),
    ("The Crown", "Chronicles the reign of Queen Elizabeth II and the events that shaped the second half of the 20th century."),
    ("The Boys", "In a world where superheroes abuse their powers, a group of vigilantes takes them down."),
    ("Fleabag", "A witty and troubled woman navigates life and love in London."),
    ("His Dark Materials", "Adaptation of Philip Pullman's trilogy, exploring a parallel universe."),
    ("The Politician", "A wealthy student navigates the cutthroat world of politics in his pursuit of the presidency."),
    ("The Morning Show", "Explores the dynamics of a morning news show in the #MeToo era."),
    ("The Sopranos", "A mob boss balances the demands of his crime family with those of his personal life."),
    ("The West Wing", "Drama following the lives of the staff in the West Wing of the White House."),
    ("Law & Order: Special Victims Unit", "Focuses on the investigation and prosecution of sexually based offenses."),
    ("Freaks and Geeks", "Follows a group of high school students in the 1980s."),
    ("Angel", "A vampire with a soul helps people in Los Angeles and battles supernatural forces."),
    ("The Practice", "Legal drama following a Boston law firm."),
    ("Roswell", "Teenagers in Roswell, New Mexico, discover they are aliens with unique powers."),
    ("Charmed", "Three sisters, witches with unique powers, battle dark forces to protect the world."),
    ("Judging Amy", "A family court judge juggles her personal and professional life."),
    ("The X-Files", "FBI agents investigate unsolved and unusual cases, often involving paranormal phenomena."),
    ("Party of Five", "Siblings navigate life after the death of their parents."),
    ("ER", "Medical drama following the emergency room staff at County General Hospital."),
    ("Buffy the Vampire Slayer", "A young woman battles vampires and other supernatural forces."),
    ("Law & Order", "Police procedural and legal drama that follows criminal investigations."),
    ("Dawson's Creek", "Teenagers in a small town navigate the challenges of adolescence and relationships."),
    ("Hana Nochi Hare: Hanadan Next Season", "Follows a new generation of students at Eitoku Academy, known for its wealthy and elite students."),
    ("Gintama 2: Yonimo Kimyo na Gintama-chan", "Live-action adaptation of the popular manga and anime series, featuring comedic and action-packed adventures."),
    ("Radiation House", "Medical drama revolving around a radiographer and his team."),
    ("Suits: Harveys Minato", "Japanese adaptation of the American legal drama 'Suits.'"),
    ("Kuragehime", "Follows a group of otaku women living together and navigating relationships."),
    ("Natsuzora", "Drama set in the 1960s, exploring the lives of two young people from different backgrounds."),
    ("Anata niwa Watasanai", "A woman works to expose the dark secrets of the elite."),
    ("Good Doctor", "A young surgeon with autism and savant syndrome faces challenges in a prestigious hospital."),
    ("Shitamachi Rocket", "Drama about a middle-aged man's journey to develop a new rocket."),
    ("Signal: Choki Mikaiketsu Jiken Sosahan", "Investigation drama involving a mysterious walkie-talkie that allows communication across time."),
    ("Unnatural", "Forensic pathologists investigate unusual and mysterious deaths."),
    ("Hana Moyu", "Historical drama set in the Meiji era, depicting the life of a woman who becomes a concubine."),
    ("Miss Sherlock", "Modern adaptation of Sherlock Holmes set in Tokyo."),
    ("Todome no Kiss", "A man gains the ability to kill anyone with a kiss and uses it to seek revenge."),
    ("BG: Personal Bodyguard", "A bodyguard protects a high-profile client while dealing with personal challenges."),
    ("Violet Evergarden", "A former soldier works as an Auto Memory Doll to understand the meaning of 'I love you.'"),
    ("Attack on Titan Season 3", "Continuation of the epic battle between humanity and giant humanoid creatures."),
    ("My Hero Academia Season 3", "The aspiring heroes of UA High School face new challenges and villains."),
    ("Devilman Crybaby", "A young man merges with a demon to fight against other demons threatening humanity."),
    ("Cells at Work!", "Anthropomorphic cells inside the human body navigate various biological processes."),
    ("The Ancient Magus' Bride", "A girl with magical abilities is taken in by a mage with a mysterious past."),
    ("Banana Fish", "A young gang leader seeks the truth behind a mysterious drug called Banana Fish."),
    ("A Place Further than the Universe", "Four high school girls embark on an expedition to Antarctica."),
    ("Zombie Land Saga", "A group of deceased girls is resurrected as idols to save Saga Prefecture."),
    ("Rascal Does Not Dream of Bunny Girl Senpai", "A boy encounters supernatural phenomena related to adolescence."),
    ("Golden Kamuy", "A soldier and an Ainu girl search for hidden Ainu gold in post-war Hokkaido."),
    ("Darling in the Franxx", "Pilots control giant mechs to protect humanity from mysterious creatures."),
    ("Steins;Gate 0", "A continuation of the science fiction series exploring time travel."),
    ("Sword Art Online: Alicization", "Kirito finds himself in a mysterious virtual world with a new set of challenges."),
    ("Goblin Slayer", "An adventurer known as Goblin Slayer specializes in hunting goblins.");