INSERT INTO broadcasts (channel_id, episode_id, start_time, end_time, number_of_view)
SELECT
    FLOOR(RAND() * 20) + 1 as channel_id,
    FLOOR(RAND() * 4990) + 1 as episode_id, -- エピソードの数によって後で変更する
    TIMESTAMPADD(SECOND, FLOOR(RAND() * 31536000), '2023-01-01') as start_time,
    TIMESTAMPADD(SECOND, FLOOR(RAND() * 31536000), TIMESTAMPADD(SECOND, FLOOR(RAND() * 31536000), '2023-01-01')) as end_time,
    FLOOR(RAND() * 999901) + 100 as number_of_view
FROM
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as a,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as b,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as c,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as d,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as e,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as f,
    (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as g
;
-- 約7.8万行