INSERT INTO seasons (season_no, name, program_id, explanation, created_at, updated_at)
SELECT
    ROW_NUMBER() OVER () AS season_no,
    CONCAT('Season ', ROW_NUMBER() OVER ()) AS name,
    FLOOR(RAND() * 50) + 1 AS program_id,
    CONCAT('Explanation for Season ', ROW_NUMBER() OVER ()) AS explanation,
    NOW() - INTERVAL FLOOR(RAND() * 730) DAY AS created_at,
    NOW() - INTERVAL FLOOR(RAND() * 730) DAY AS updated_at
FROM
    (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS numbers
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS numbers2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) AS numbers3
;

INSERT INTO seasons (name, season_no, program_id, explanation) VALUES
    ('Season 3', 3, 11, 'This is the first season of an exciting drama with a thrilling storyline.'),
    ('Season 12', 12, 20, 'In this season, the story unfolds with unexpected twists and turns.'),
    ('Season 6', 6, 5, 'A new chapter begins with Season 3, featuring intense drama and compelling characters.'),
    ('Season 19', 19, 7, 'As the drama continues in Season 4, the characters face new challenges and dilemmas.'),
    ('Season 1', 1, 2, 'Season 5 takes you on a roller-coaster ride of emotions with its gripping narrative.'),
    ('Season 8', 8, 6, 'Get ready for more suspense and drama in Season 6 as the plot thickens.'),
    ('Season 17', 17, 9, "In this season, the characters' fates are intertwined, leading to dramatic confrontations."),
    ('Season 2', 2, 18, 'The storyline in Season 8 is filled with surprises and shocking revelations.'),
    ('Season 14', 14, 4, 'As Season 9 unfolds, the tension reaches its peak, keeping you hooked.'),
    ('Season 5', 5, 10, 'Prepare for an epic conclusion as Season 10 brings the story to its climax.'),
    ('Season 11', 11, 14, 'In this season, new characters are introduced, adding depth to the narrative.'),
    ('Season 19', 19, 3, 'Season 12 is a roller-coaster of emotions, with characters facing personal struggles.'),
    ('Season 15', 15, 15, 'As the drama unfolds in Season 13, secrets are revealed, changing the game.'),
    ('Season 20', 20, 16, 'This season is all about redemption and revenge, making it a thrilling watch.'),
    ('Season 4', 4, 1, 'In Season 15, the characters are on a quest for justice in a world filled with deception.'),
    ('Season 13', 13, 8, "As Season 16 unfolds, the characters' loyalties are tested."),
    ('Season 16', 16, 13, 'Season 17 delves into the past, unraveling long-buried secrets and mysteries.'),
    ('Season 9', 9, 12, 'The drama intensifies in Season 18 as alliances are forged and broken.'),
    ('Season 7', 7, 19, 'In this season, the characters face a moral dilemma that changes their lives.'),
    ('Season 18', 18, 17, 'The 20th season is a heart-pounding journey through the complexities of human nature.'),
    ('Season 10', 10, 20, 'As Season 21 unfolds, the characters confront their past and seek redemption.'),
    ('Season 15', 15, 20, "In this season, the characters' destinies are entwined in unexpected ways."),
    ('Season 14', 14, 7, 'Season 23 is filled with shocking twists and turns that will leave you amazed.'),
    ('Season 2', 2, 8, 'Get ready for an intense and action-packed season in Season 24.'),
    ('Season 20', 20, 15, 'As the story continues in Season 25, the characters face their darkest fears.'),
    ('Season 14', 14, 12, 'Season 26 takes you on a journey through love, betrayal, and revenge.'),
    ('Season 19', 19, 10, 'In this season, the characters face a moral crossroads.'),
    ('Season 18', 18, 1, 'Season 38 is a thrilling mix of drama, action, and unexpected alliances.'),
    ('Season 9', 9, 16, "In this season, the characters' loyalty is tested like never before."),
    ('Season 15', 15, 5, 'Season 40 is a culmination of all the events leading to an explosive climax.'),
    ('Season 11', 11, 3, 'Prepare for more twists and turns as Season 41 unravels the truth.'),
    ('Season 10', 10, 19, "In this season, the characters' pasts come back to haunt them, changing the game."),
    ('Season 12', 12, 17, 'Season 43 takes you on a roller-coaster of emotions with its gripping narrative.'),
    ('Season 19', 19, 4, 'The storyline in Season 44 is filled with surprises and shocking revelations.'),
    ('Season 8', 8, 2, 'As the drama continues in Season 45, the characters face new challenges and dilemmas.'),
    ('Season 7', 7, 14, 'Get ready for more suspense and drama in Season 46 as the plot thickens.'),
    ('Season 4', 4, 9, 'This season is all about redemption and revenge, making it a thrilling watch.'),
    ('Season 3', 3, 16, 'In Season 48, the characters are on a quest for justice in a world filled with deception.'),
    ('Season 1', 1, 5, 'As the story unfolds in Season 49, secrets are revealed, changing the game.'),
    ('Season 20', 20, 8, 'Season 50 marks the epic conclusion of the series, with an unforgettable finale.'),
    ('Season 12', 12, 7, "In this season, the characters' fates are intertwined, leading to dramatic confrontations."),
    ('Season 6', 6, 3, 'The storyline in Season 8 is filled with surprises and shocking revelations.'),
    ('Season 15', 15, 11, 'As Season 9 unfolds, the tension reaches its peak, keeping you hooked.'),
    ('Season 13', 13, 20, 'Prepare for an epic conclusion as Season 10 brings the story to its climax.'),
    ('Season 16', 16, 6, 'In this season, new characters are introduced, adding depth to the narrative.'),
    ('Season 10', 10, 19, 'Season 12 is a roller-coaster of emotions, with characters facing personal struggles.'),
    ('Season 11', 11, 13, 'As the drama unfolds in Season 13, secrets are revealed, changing the game.'),
    ('Season 19', 19, 10, 'This season is all about redemption and revenge, making it a thrilling watch.'),
    ('Season 20', 20, 12, 'In Season 15, the characters are on a quest for justice in a world filled with deception.'),
    ('Season 14', 14, 16, "As Season 16 unfolds, the characters' loyalties are tested."),
    ('Season 17', 17, 4, 'Season 17 delves into the past, unraveling long-buried secrets and mysteries.'),
    ('Season 8', 8, 19, 'The drama intensifies in Season 18 as alliances are forged and broken.'),
    ('Season 18', 18, 7, 'In this season, the characters face a moral dilemma that changes their lives.'),
    ('Season 9', 9, 1, 'The 20th season is a heart-pounding journey through the complexities of human nature.'),
    ('Season 7', 7, 5, 'As Season 21 unfolds, the characters confront their past and seek redemption.'),
    ('Season 8', 8, 14, "In this season, the characters' destinies are entwined in unexpected ways."),
    ('Season 14', 14, 12, 'Season 23 is filled with shocking twists and turns that will leave you amazed.'),
    ('Season 3', 3, 2, 'Get ready for an intense and action-packed season in Season 24.'),
    ('Season 20', 20, 9, 'As the story continues in Season 25, the characters face their darkest fears.'),
    ('Season 14', 14, 18, 'Season 26 takes you on a journey through love, betrayal, and revenge.'),
    ('Season 6', 6, 20, 'In this season, the characters face a moral crossroads.'),
    ('Season 17', 17, 8, 'Season 38 is a thrilling mix of drama, action, and unexpected alliances.'),
    ('Season 18', 18, 15, "In this season, the characters' loyalty is tested like never before.");