INSERT INTO genres (program_id, genre)
SELECT
  FLOOR(1 + RAND() * 160), -- program_idを1から150までのランダムな値で生成
  CASE
    WHEN RAND() < 0.1 THEN 'Action'
    WHEN RAND() < 0.2 THEN 'Comedy'
    WHEN RAND() < 0.3 THEN 'Drama'
    WHEN RAND() < 0.4 THEN 'Sci-Fi'
    WHEN RAND() < 0.5 THEN 'Horror'
    WHEN RAND() < 0.6 THEN 'Romance'
    WHEN RAND() < 0.7 THEN 'Adventure'
    WHEN RAND() < 0.8 THEN 'Fantasy'
    WHEN RAND() < 0.9 THEN 'Mystery'
    ELSE 'Thriller'
  END AS genre
FROM
  (SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS a,
  (SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS b,
  (SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS c
;